version: "2.2"
services:
    nginx:
        image: nginx
        ports:
            - "8080:8080"
        links:
            - "php-fpm"
        volumes:
            - /home/workspace/project/:/var/www/html/
            - /home/workspace/nginx/conf.d/:/etc/nginx/conf.d/
            - /home/workspace/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
            - /home/workspace/nginx/logs:/var/log/nginx/
        depends_on:
            - php-fpm
        container_name: nginx
        networks:
            - app
    php-fpm:
        #image: php:7.2-fpm
        build: ./php-fpm
        ports:
            - "9000:9000"
        volumes:
            - /home/workspace/project/:/var/www/html/
            - /home/workspace/project/php-fpm/conf/php.ini:/usr/local/etc/php/php.ini:rw
            #- /home/workspace/project/php-fpm/conf/php-fpm.d/:/usr/local/etc/php-fpm.d/
            - /home/workspace/project/php-fpm/log/:/var/log/dnmp/:rw
        depends_on:
            - mysql
            - redis
        environment:
            - TZ=Asia/Shanghai
        links:
          - "mysql"
          - "redis"
        container_name: php-fpm
        networks:
            - app
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - /home/workspace/mysql/conf:/etc/mysql/conf.d
            - /home/workspace/mysql/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123456
        container_name: mysql
        networks:
            - app
    redis:
        image: redis
        ports:
            - "6379:6379"
        networks:
            - app
        container_name: redis
networks:
    app:
        driver: bridge

