version: "2.2"
services:
    nginx:
        image: nginx
        ports:
            - "80:80"
        links:
            - "php-fpm"
        volumes:
            - /E/workspace/:/var/www/html/
            - /E/my-docker-config/nginx/conf.d/:/etc/nginx/conf.d/
            - /E/my-docker-config/nginx/nginx.conf:/etc/nginx/nginx.conf:rw
            - /E/my-docker-config/nginx/logs:/etc/nginx/logs/
        depends_on:
            - php-fpm
        container_name: nginx
        networks:
            - app
    php-fpm:
        #image: php:7.2-fpm
        build: ./php-fpm
        ports:
            - "9000:9000"
            - "22:22"
        volumes:
            - /E/workspace/:/var/www/html/
            - /E/my-docker-config/php-fpm/conf/php.ini:/usr/local/etc/php/php.ini:rw
            #- /home/workspace/project/php-fpm/conf/php-fpm.d/:/usr/local/etc/php-fpm.d/
            - /E/my-docker-config/php-fpm/log/:/var/log/dnmp/:rw
        depends_on:
            - mysql
            - redis
        environment:
            - TZ=Asia/Shanghai
        links:
          - "mysql"
          - "redis"
        container_name: php-fpm
        networks:
            - app
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - /E/my-docker-config/mysql/conf:/etc/mysql/conf.d
            - /E/my-docker-config/mysql/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123456
        container_name: mysql
        networks:
            - app
    redis:
        image: redis
        ports:
            - "6379:6379"
        networks:
            - app
        container_name: redis
    redis-manage:
        image: reasonduan/redis-manager
        ports:
            - "8182:8182"
        environment: 
            DATASOURCE_DATABASE: redis_manager
            DATASOURCE_URL: jdbc:mysql://mysql/redis_manager?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
            DATASOURCE_USERNAME: root
            DATASOURCE_PASSWORD: 123456
        links:
            - "mysql"
        container_name: redis-manage
        networks:
            - app
networks:
    app:
        driver: bridge

